/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostCreateTweet200Response - struct for PostCreateTweet200Response
type PostCreateTweet200Response struct {
	CreateTweetResponse *CreateTweetResponse
	Errors              *Errors
}

// CreateTweetResponseAsPostCreateTweet200Response is a convenience function that returns CreateTweetResponse wrapped in PostCreateTweet200Response
func CreateTweetResponseAsPostCreateTweet200Response(v *CreateTweetResponse) PostCreateTweet200Response {
	return PostCreateTweet200Response{
		CreateTweetResponse: v,
	}
}

// ErrorsAsPostCreateTweet200Response is a convenience function that returns Errors wrapped in PostCreateTweet200Response
func ErrorsAsPostCreateTweet200Response(v *Errors) PostCreateTweet200Response {
	return PostCreateTweet200Response{
		Errors: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostCreateTweet200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateTweetResponse
	err = newStrictDecoder(data).Decode(&dst.CreateTweetResponse)
	if err == nil {
		jsonCreateTweetResponse, _ := json.Marshal(dst.CreateTweetResponse)
		if string(jsonCreateTweetResponse) == "{}" { // empty struct
			dst.CreateTweetResponse = nil
		} else {
			if err = validator.Validate(dst.CreateTweetResponse); err != nil {
				dst.CreateTweetResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateTweetResponse = nil
	}

	// try to unmarshal data into Errors
	err = newStrictDecoder(data).Decode(&dst.Errors)
	if err == nil {
		jsonErrors, _ := json.Marshal(dst.Errors)
		if string(jsonErrors) == "{}" { // empty struct
			dst.Errors = nil
		} else {
			if err = validator.Validate(dst.Errors); err != nil {
				dst.Errors = nil
			} else {
				match++
			}
		}
	} else {
		dst.Errors = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateTweetResponse = nil
		dst.Errors = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostCreateTweet200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostCreateTweet200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostCreateTweet200Response) MarshalJSON() ([]byte, error) {
	if src.CreateTweetResponse != nil {
		return json.Marshal(&src.CreateTweetResponse)
	}

	if src.Errors != nil {
		return json.Marshal(&src.Errors)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostCreateTweet200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CreateTweetResponse != nil {
		return obj.CreateTweetResponse
	}

	if obj.Errors != nil {
		return obj.Errors
	}

	// all schemas are nil
	return nil
}

type NullablePostCreateTweet200Response struct {
	value *PostCreateTweet200Response
	isSet bool
}

func (v NullablePostCreateTweet200Response) Get() *PostCreateTweet200Response {
	return v.value
}

func (v *NullablePostCreateTweet200Response) Set(val *PostCreateTweet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCreateTweet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCreateTweet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCreateTweet200Response(val *PostCreateTweet200Response) *NullablePostCreateTweet200Response {
	return &NullablePostCreateTweet200Response{value: val, isSet: true}
}

func (v NullablePostCreateTweet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCreateTweet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
