/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SocialContextLandingUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocialContextLandingUrl{}

// SocialContextLandingUrl struct for SocialContextLandingUrl
type SocialContextLandingUrl struct {
	Url                *string             `json:"url,omitempty"`
	UrlType            *string             `json:"urlType,omitempty"`
	UrtEndpointOptions *UrtEndpointOptions `json:"urtEndpointOptions,omitempty"`
}

// NewSocialContextLandingUrl instantiates a new SocialContextLandingUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocialContextLandingUrl() *SocialContextLandingUrl {
	this := SocialContextLandingUrl{}
	return &this
}

// NewSocialContextLandingUrlWithDefaults instantiates a new SocialContextLandingUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocialContextLandingUrlWithDefaults() *SocialContextLandingUrl {
	this := SocialContextLandingUrl{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SocialContextLandingUrl) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialContextLandingUrl) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SocialContextLandingUrl) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SocialContextLandingUrl) SetUrl(v string) {
	o.Url = &v
}

// GetUrlType returns the UrlType field value if set, zero value otherwise.
func (o *SocialContextLandingUrl) GetUrlType() string {
	if o == nil || IsNil(o.UrlType) {
		var ret string
		return ret
	}
	return *o.UrlType
}

// GetUrlTypeOk returns a tuple with the UrlType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialContextLandingUrl) GetUrlTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UrlType) {
		return nil, false
	}
	return o.UrlType, true
}

// HasUrlType returns a boolean if a field has been set.
func (o *SocialContextLandingUrl) HasUrlType() bool {
	if o != nil && !IsNil(o.UrlType) {
		return true
	}

	return false
}

// SetUrlType gets a reference to the given string and assigns it to the UrlType field.
func (o *SocialContextLandingUrl) SetUrlType(v string) {
	o.UrlType = &v
}

// GetUrtEndpointOptions returns the UrtEndpointOptions field value if set, zero value otherwise.
func (o *SocialContextLandingUrl) GetUrtEndpointOptions() UrtEndpointOptions {
	if o == nil || IsNil(o.UrtEndpointOptions) {
		var ret UrtEndpointOptions
		return ret
	}
	return *o.UrtEndpointOptions
}

// GetUrtEndpointOptionsOk returns a tuple with the UrtEndpointOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialContextLandingUrl) GetUrtEndpointOptionsOk() (*UrtEndpointOptions, bool) {
	if o == nil || IsNil(o.UrtEndpointOptions) {
		return nil, false
	}
	return o.UrtEndpointOptions, true
}

// HasUrtEndpointOptions returns a boolean if a field has been set.
func (o *SocialContextLandingUrl) HasUrtEndpointOptions() bool {
	if o != nil && !IsNil(o.UrtEndpointOptions) {
		return true
	}

	return false
}

// SetUrtEndpointOptions gets a reference to the given UrtEndpointOptions and assigns it to the UrtEndpointOptions field.
func (o *SocialContextLandingUrl) SetUrtEndpointOptions(v UrtEndpointOptions) {
	o.UrtEndpointOptions = &v
}

func (o SocialContextLandingUrl) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocialContextLandingUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.UrlType) {
		toSerialize["urlType"] = o.UrlType
	}
	if !IsNil(o.UrtEndpointOptions) {
		toSerialize["urtEndpointOptions"] = o.UrtEndpointOptions
	}
	return toSerialize, nil
}

type NullableSocialContextLandingUrl struct {
	value *SocialContextLandingUrl
	isSet bool
}

func (v NullableSocialContextLandingUrl) Get() *SocialContextLandingUrl {
	return v.value
}

func (v *NullableSocialContextLandingUrl) Set(val *SocialContextLandingUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableSocialContextLandingUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableSocialContextLandingUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocialContextLandingUrl(val *SocialContextLandingUrl) *NullableSocialContextLandingUrl {
	return &NullableSocialContextLandingUrl{value: val, isSet: true}
}

func (v NullableSocialContextLandingUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocialContextLandingUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
