/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostCreateBookmarkRequestVariables type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCreateBookmarkRequestVariables{}

// PostCreateBookmarkRequestVariables struct for PostCreateBookmarkRequestVariables
type PostCreateBookmarkRequestVariables struct {
	TweetId string `json:"tweet_id"`
}

type _PostCreateBookmarkRequestVariables PostCreateBookmarkRequestVariables

// NewPostCreateBookmarkRequestVariables instantiates a new PostCreateBookmarkRequestVariables object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCreateBookmarkRequestVariables(tweetId string) *PostCreateBookmarkRequestVariables {
	this := PostCreateBookmarkRequestVariables{}
	this.TweetId = tweetId
	return &this
}

// NewPostCreateBookmarkRequestVariablesWithDefaults instantiates a new PostCreateBookmarkRequestVariables object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCreateBookmarkRequestVariablesWithDefaults() *PostCreateBookmarkRequestVariables {
	this := PostCreateBookmarkRequestVariables{}
	var tweetId string = "1349129669258448897"
	this.TweetId = tweetId
	return &this
}

// GetTweetId returns the TweetId field value
func (o *PostCreateBookmarkRequestVariables) GetTweetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TweetId
}

// GetTweetIdOk returns a tuple with the TweetId field value
// and a boolean to check if the value has been set.
func (o *PostCreateBookmarkRequestVariables) GetTweetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TweetId, true
}

// SetTweetId sets field value
func (o *PostCreateBookmarkRequestVariables) SetTweetId(v string) {
	o.TweetId = v
}

func (o PostCreateBookmarkRequestVariables) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCreateBookmarkRequestVariables) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tweet_id"] = o.TweetId
	return toSerialize, nil
}

func (o *PostCreateBookmarkRequestVariables) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tweet_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCreateBookmarkRequestVariables := _PostCreateBookmarkRequestVariables{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCreateBookmarkRequestVariables)

	if err != nil {
		return err
	}

	*o = PostCreateBookmarkRequestVariables(varPostCreateBookmarkRequestVariables)

	return err
}

type NullablePostCreateBookmarkRequestVariables struct {
	value *PostCreateBookmarkRequestVariables
	isSet bool
}

func (v NullablePostCreateBookmarkRequestVariables) Get() *PostCreateBookmarkRequestVariables {
	return v.value
}

func (v *NullablePostCreateBookmarkRequestVariables) Set(val *PostCreateBookmarkRequestVariables) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCreateBookmarkRequestVariables) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCreateBookmarkRequestVariables) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCreateBookmarkRequestVariables(val *PostCreateBookmarkRequestVariables) *NullablePostCreateBookmarkRequestVariables {
	return &NullablePostCreateBookmarkRequestVariables{value: val, isSet: true}
}

func (v NullablePostCreateBookmarkRequestVariables) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCreateBookmarkRequestVariables) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


