/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimelineClearCache type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineClearCache{}

// TimelineClearCache struct for TimelineClearCache
type TimelineClearCache struct {
	Type InstructionType `json:"type"`
}

type _TimelineClearCache TimelineClearCache

// NewTimelineClearCache instantiates a new TimelineClearCache object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineClearCache(type_ InstructionType) *TimelineClearCache {
	this := TimelineClearCache{}
	this.Type = type_
	return &this
}

// NewTimelineClearCacheWithDefaults instantiates a new TimelineClearCache object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineClearCacheWithDefaults() *TimelineClearCache {
	this := TimelineClearCache{}
	return &this
}

// GetType returns the Type field value
func (o *TimelineClearCache) GetType() InstructionType {
	if o == nil {
		var ret InstructionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TimelineClearCache) GetTypeOk() (*InstructionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TimelineClearCache) SetType(v InstructionType) {
	o.Type = v
}

func (o TimelineClearCache) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineClearCache) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TimelineClearCache) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimelineClearCache := _TimelineClearCache{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimelineClearCache)

	if err != nil {
		return err
	}

	*o = TimelineClearCache(varTimelineClearCache)

	return err
}

type NullableTimelineClearCache struct {
	value *TimelineClearCache
	isSet bool
}

func (v NullableTimelineClearCache) Get() *TimelineClearCache {
	return v.value
}

func (v *NullableTimelineClearCache) Set(val *TimelineClearCache) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineClearCache) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineClearCache) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineClearCache(val *TimelineClearCache) *NullableTimelineClearCache {
	return &NullableTimelineClearCache{value: val, isSet: true}
}

func (v NullableTimelineClearCache) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineClearCache) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


