/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BirdwatchPivotFooter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BirdwatchPivotFooter{}

// BirdwatchPivotFooter struct for BirdwatchPivotFooter
type BirdwatchPivotFooter struct {
	Entities []BirdwatchEntity `json:"entities"`
	Text     string            `json:"text"`
}

type _BirdwatchPivotFooter BirdwatchPivotFooter

// NewBirdwatchPivotFooter instantiates a new BirdwatchPivotFooter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBirdwatchPivotFooter(entities []BirdwatchEntity, text string) *BirdwatchPivotFooter {
	this := BirdwatchPivotFooter{}
	this.Entities = entities
	this.Text = text
	return &this
}

// NewBirdwatchPivotFooterWithDefaults instantiates a new BirdwatchPivotFooter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBirdwatchPivotFooterWithDefaults() *BirdwatchPivotFooter {
	this := BirdwatchPivotFooter{}
	return &this
}

// GetEntities returns the Entities field value
func (o *BirdwatchPivotFooter) GetEntities() []BirdwatchEntity {
	if o == nil {
		var ret []BirdwatchEntity
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *BirdwatchPivotFooter) GetEntitiesOk() ([]BirdwatchEntity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *BirdwatchPivotFooter) SetEntities(v []BirdwatchEntity) {
	o.Entities = v
}

// GetText returns the Text field value
func (o *BirdwatchPivotFooter) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *BirdwatchPivotFooter) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *BirdwatchPivotFooter) SetText(v string) {
	o.Text = v
}

func (o BirdwatchPivotFooter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BirdwatchPivotFooter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entities"] = o.Entities
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *BirdwatchPivotFooter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entities",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBirdwatchPivotFooter := _BirdwatchPivotFooter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBirdwatchPivotFooter)

	if err != nil {
		return err
	}

	*o = BirdwatchPivotFooter(varBirdwatchPivotFooter)

	return err
}

type NullableBirdwatchPivotFooter struct {
	value *BirdwatchPivotFooter
	isSet bool
}

func (v NullableBirdwatchPivotFooter) Get() *BirdwatchPivotFooter {
	return v.value
}

func (v *NullableBirdwatchPivotFooter) Set(val *BirdwatchPivotFooter) {
	v.value = val
	v.isSet = true
}

func (v NullableBirdwatchPivotFooter) IsSet() bool {
	return v.isSet
}

func (v *NullableBirdwatchPivotFooter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBirdwatchPivotFooter(val *BirdwatchPivotFooter) *NullableBirdwatchPivotFooter {
	return &NullableBirdwatchPivotFooter{value: val, isSet: true}
}

func (v NullableBirdwatchPivotFooter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBirdwatchPivotFooter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
