/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostCreateTweetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCreateTweetRequest{}

// PostCreateTweetRequest struct for PostCreateTweetRequest
type PostCreateTweetRequest struct {
	Features PostCreateTweetRequestFeatures `json:"features"`
	QueryId string `json:"queryId"`
	Variables PostCreateTweetRequestVariables `json:"variables"`
}

type _PostCreateTweetRequest PostCreateTweetRequest

// NewPostCreateTweetRequest instantiates a new PostCreateTweetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCreateTweetRequest(features PostCreateTweetRequestFeatures, queryId string, variables PostCreateTweetRequestVariables) *PostCreateTweetRequest {
	this := PostCreateTweetRequest{}
	this.Features = features
	this.QueryId = queryId
	this.Variables = variables
	return &this
}

// NewPostCreateTweetRequestWithDefaults instantiates a new PostCreateTweetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCreateTweetRequestWithDefaults() *PostCreateTweetRequest {
	this := PostCreateTweetRequest{}
	var queryId string = "xT36w0XM3A8jDynpkram2A"
	this.QueryId = queryId
	return &this
}

// GetFeatures returns the Features field value
func (o *PostCreateTweetRequest) GetFeatures() PostCreateTweetRequestFeatures {
	if o == nil {
		var ret PostCreateTweetRequestFeatures
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *PostCreateTweetRequest) GetFeaturesOk() (*PostCreateTweetRequestFeatures, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *PostCreateTweetRequest) SetFeatures(v PostCreateTweetRequestFeatures) {
	o.Features = v
}

// GetQueryId returns the QueryId field value
func (o *PostCreateTweetRequest) GetQueryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryId
}

// GetQueryIdOk returns a tuple with the QueryId field value
// and a boolean to check if the value has been set.
func (o *PostCreateTweetRequest) GetQueryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryId, true
}

// SetQueryId sets field value
func (o *PostCreateTweetRequest) SetQueryId(v string) {
	o.QueryId = v
}

// GetVariables returns the Variables field value
func (o *PostCreateTweetRequest) GetVariables() PostCreateTweetRequestVariables {
	if o == nil {
		var ret PostCreateTweetRequestVariables
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *PostCreateTweetRequest) GetVariablesOk() (*PostCreateTweetRequestVariables, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Variables, true
}

// SetVariables sets field value
func (o *PostCreateTweetRequest) SetVariables(v PostCreateTweetRequestVariables) {
	o.Variables = v
}

func (o PostCreateTweetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCreateTweetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["features"] = o.Features
	toSerialize["queryId"] = o.QueryId
	toSerialize["variables"] = o.Variables
	return toSerialize, nil
}

func (o *PostCreateTweetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"features",
		"queryId",
		"variables",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCreateTweetRequest := _PostCreateTweetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCreateTweetRequest)

	if err != nil {
		return err
	}

	*o = PostCreateTweetRequest(varPostCreateTweetRequest)

	return err
}

type NullablePostCreateTweetRequest struct {
	value *PostCreateTweetRequest
	isSet bool
}

func (v NullablePostCreateTweetRequest) Get() *PostCreateTweetRequest {
	return v.value
}

func (v *NullablePostCreateTweetRequest) Set(val *PostCreateTweetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCreateTweetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCreateTweetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCreateTweetRequest(val *PostCreateTweetRequest) *NullablePostCreateTweetRequest {
	return &NullablePostCreateTweetRequest{value: val, isSet: true}
}

func (v NullablePostCreateTweetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCreateTweetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


