/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdditionalMediaInfoCallToActions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalMediaInfoCallToActions{}

// AdditionalMediaInfoCallToActions struct for AdditionalMediaInfoCallToActions
type AdditionalMediaInfoCallToActions struct {
	VisitSite *AdditionalMediaInfoCallToActionsUrl `json:"visit_site,omitempty"`
	WatchNow *AdditionalMediaInfoCallToActionsUrl `json:"watch_now,omitempty"`
}

// NewAdditionalMediaInfoCallToActions instantiates a new AdditionalMediaInfoCallToActions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalMediaInfoCallToActions() *AdditionalMediaInfoCallToActions {
	this := AdditionalMediaInfoCallToActions{}
	return &this
}

// NewAdditionalMediaInfoCallToActionsWithDefaults instantiates a new AdditionalMediaInfoCallToActions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalMediaInfoCallToActionsWithDefaults() *AdditionalMediaInfoCallToActions {
	this := AdditionalMediaInfoCallToActions{}
	return &this
}

// GetVisitSite returns the VisitSite field value if set, zero value otherwise.
func (o *AdditionalMediaInfoCallToActions) GetVisitSite() AdditionalMediaInfoCallToActionsUrl {
	if o == nil || IsNil(o.VisitSite) {
		var ret AdditionalMediaInfoCallToActionsUrl
		return ret
	}
	return *o.VisitSite
}

// GetVisitSiteOk returns a tuple with the VisitSite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalMediaInfoCallToActions) GetVisitSiteOk() (*AdditionalMediaInfoCallToActionsUrl, bool) {
	if o == nil || IsNil(o.VisitSite) {
		return nil, false
	}
	return o.VisitSite, true
}

// HasVisitSite returns a boolean if a field has been set.
func (o *AdditionalMediaInfoCallToActions) HasVisitSite() bool {
	if o != nil && !IsNil(o.VisitSite) {
		return true
	}

	return false
}

// SetVisitSite gets a reference to the given AdditionalMediaInfoCallToActionsUrl and assigns it to the VisitSite field.
func (o *AdditionalMediaInfoCallToActions) SetVisitSite(v AdditionalMediaInfoCallToActionsUrl) {
	o.VisitSite = &v
}

// GetWatchNow returns the WatchNow field value if set, zero value otherwise.
func (o *AdditionalMediaInfoCallToActions) GetWatchNow() AdditionalMediaInfoCallToActionsUrl {
	if o == nil || IsNil(o.WatchNow) {
		var ret AdditionalMediaInfoCallToActionsUrl
		return ret
	}
	return *o.WatchNow
}

// GetWatchNowOk returns a tuple with the WatchNow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalMediaInfoCallToActions) GetWatchNowOk() (*AdditionalMediaInfoCallToActionsUrl, bool) {
	if o == nil || IsNil(o.WatchNow) {
		return nil, false
	}
	return o.WatchNow, true
}

// HasWatchNow returns a boolean if a field has been set.
func (o *AdditionalMediaInfoCallToActions) HasWatchNow() bool {
	if o != nil && !IsNil(o.WatchNow) {
		return true
	}

	return false
}

// SetWatchNow gets a reference to the given AdditionalMediaInfoCallToActionsUrl and assigns it to the WatchNow field.
func (o *AdditionalMediaInfoCallToActions) SetWatchNow(v AdditionalMediaInfoCallToActionsUrl) {
	o.WatchNow = &v
}

func (o AdditionalMediaInfoCallToActions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalMediaInfoCallToActions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VisitSite) {
		toSerialize["visit_site"] = o.VisitSite
	}
	if !IsNil(o.WatchNow) {
		toSerialize["watch_now"] = o.WatchNow
	}
	return toSerialize, nil
}

type NullableAdditionalMediaInfoCallToActions struct {
	value *AdditionalMediaInfoCallToActions
	isSet bool
}

func (v NullableAdditionalMediaInfoCallToActions) Get() *AdditionalMediaInfoCallToActions {
	return v.value
}

func (v *NullableAdditionalMediaInfoCallToActions) Set(val *AdditionalMediaInfoCallToActions) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalMediaInfoCallToActions) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalMediaInfoCallToActions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalMediaInfoCallToActions(val *AdditionalMediaInfoCallToActions) *NullableAdditionalMediaInfoCallToActions {
	return &NullableAdditionalMediaInfoCallToActions{value: val, isSet: true}
}

func (v NullableAdditionalMediaInfoCallToActions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalMediaInfoCallToActions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


