/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BookmarksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarksResponse{}

// BookmarksResponse struct for BookmarksResponse
type BookmarksResponse struct {
	Data BookmarksResponseData `json:"data"`
}

type _BookmarksResponse BookmarksResponse

// NewBookmarksResponse instantiates a new BookmarksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarksResponse(data BookmarksResponseData) *BookmarksResponse {
	this := BookmarksResponse{}
	this.Data = data
	return &this
}

// NewBookmarksResponseWithDefaults instantiates a new BookmarksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarksResponseWithDefaults() *BookmarksResponse {
	this := BookmarksResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BookmarksResponse) GetData() BookmarksResponseData {
	if o == nil {
		var ret BookmarksResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BookmarksResponse) GetDataOk() (*BookmarksResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BookmarksResponse) SetData(v BookmarksResponseData) {
	o.Data = v
}

func (o BookmarksResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BookmarksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmarksResponse := _BookmarksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmarksResponse)

	if err != nil {
		return err
	}

	*o = BookmarksResponse(varBookmarksResponse)

	return err
}

type NullableBookmarksResponse struct {
	value *BookmarksResponse
	isSet bool
}

func (v NullableBookmarksResponse) Get() *BookmarksResponse {
	return v.value
}

func (v *NullableBookmarksResponse) Set(val *BookmarksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarksResponse(val *BookmarksResponse) *NullableBookmarksResponse {
	return &NullableBookmarksResponse{value: val, isSet: true}
}

func (v NullableBookmarksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
