/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostCreateRetweetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCreateRetweetRequest{}

// PostCreateRetweetRequest struct for PostCreateRetweetRequest
type PostCreateRetweetRequest struct {
	QueryId   string                            `json:"queryId"`
	Variables PostCreateRetweetRequestVariables `json:"variables"`
}

type _PostCreateRetweetRequest PostCreateRetweetRequest

// NewPostCreateRetweetRequest instantiates a new PostCreateRetweetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCreateRetweetRequest(queryId string, variables PostCreateRetweetRequestVariables) *PostCreateRetweetRequest {
	this := PostCreateRetweetRequest{}
	this.QueryId = queryId
	this.Variables = variables
	return &this
}

// NewPostCreateRetweetRequestWithDefaults instantiates a new PostCreateRetweetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCreateRetweetRequestWithDefaults() *PostCreateRetweetRequest {
	this := PostCreateRetweetRequest{}
	var queryId string = "ojPdsZsimiJrUGLR1sjUtA"
	this.QueryId = queryId
	return &this
}

// GetQueryId returns the QueryId field value
func (o *PostCreateRetweetRequest) GetQueryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryId
}

// GetQueryIdOk returns a tuple with the QueryId field value
// and a boolean to check if the value has been set.
func (o *PostCreateRetweetRequest) GetQueryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryId, true
}

// SetQueryId sets field value
func (o *PostCreateRetweetRequest) SetQueryId(v string) {
	o.QueryId = v
}

// GetVariables returns the Variables field value
func (o *PostCreateRetweetRequest) GetVariables() PostCreateRetweetRequestVariables {
	if o == nil {
		var ret PostCreateRetweetRequestVariables
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *PostCreateRetweetRequest) GetVariablesOk() (*PostCreateRetweetRequestVariables, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Variables, true
}

// SetVariables sets field value
func (o *PostCreateRetweetRequest) SetVariables(v PostCreateRetweetRequestVariables) {
	o.Variables = v
}

func (o PostCreateRetweetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCreateRetweetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queryId"] = o.QueryId
	toSerialize["variables"] = o.Variables
	return toSerialize, nil
}

func (o *PostCreateRetweetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queryId",
		"variables",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCreateRetweetRequest := _PostCreateRetweetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCreateRetweetRequest)

	if err != nil {
		return err
	}

	*o = PostCreateRetweetRequest(varPostCreateRetweetRequest)

	return err
}

type NullablePostCreateRetweetRequest struct {
	value *PostCreateRetweetRequest
	isSet bool
}

func (v NullablePostCreateRetweetRequest) Get() *PostCreateRetweetRequest {
	return v.value
}

func (v *NullablePostCreateRetweetRequest) Set(val *PostCreateRetweetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCreateRetweetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCreateRetweetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCreateRetweetRequest(val *PostCreateRetweetRequest) *NullablePostCreateRetweetRequest {
	return &NullablePostCreateRetweetRequest{value: val, isSet: true}
}

func (v NullablePostCreateRetweetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCreateRetweetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
