/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileResponse{}

// ProfileResponse struct for ProfileResponse
type ProfileResponse struct {
	Data ProfileResponseData `json:"data"`
}

type _ProfileResponse ProfileResponse

// NewProfileResponse instantiates a new ProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileResponse(data ProfileResponseData) *ProfileResponse {
	this := ProfileResponse{}
	this.Data = data
	return &this
}

// NewProfileResponseWithDefaults instantiates a new ProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileResponseWithDefaults() *ProfileResponse {
	this := ProfileResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ProfileResponse) GetData() ProfileResponseData {
	if o == nil {
		var ret ProfileResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ProfileResponse) GetDataOk() (*ProfileResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ProfileResponse) SetData(v ProfileResponseData) {
	o.Data = v
}

func (o ProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ProfileResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileResponse := _ProfileResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfileResponse)

	if err != nil {
		return err
	}

	*o = ProfileResponse(varProfileResponse)

	return err
}

type NullableProfileResponse struct {
	value *ProfileResponse
	isSet bool
}

func (v NullableProfileResponse) Get() *ProfileResponse {
	return v.value
}

func (v *NullableProfileResponse) Set(val *ProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileResponse(val *ProfileResponse) *NullableProfileResponse {
	return &NullableProfileResponse{value: val, isSet: true}
}

func (v NullableProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


