/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TweetInterstitialRevealText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TweetInterstitialRevealText{}

// TweetInterstitialRevealText struct for TweetInterstitialRevealText
type TweetInterstitialRevealText struct {
	Entities []TweetInterstitialTextEntity `json:"entities"`
	Rtl      bool                          `json:"rtl"`
	Text     string                        `json:"text"`
}

type _TweetInterstitialRevealText TweetInterstitialRevealText

// NewTweetInterstitialRevealText instantiates a new TweetInterstitialRevealText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetInterstitialRevealText(entities []TweetInterstitialTextEntity, rtl bool, text string) *TweetInterstitialRevealText {
	this := TweetInterstitialRevealText{}
	this.Entities = entities
	this.Rtl = rtl
	this.Text = text
	return &this
}

// NewTweetInterstitialRevealTextWithDefaults instantiates a new TweetInterstitialRevealText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetInterstitialRevealTextWithDefaults() *TweetInterstitialRevealText {
	this := TweetInterstitialRevealText{}
	return &this
}

// GetEntities returns the Entities field value
func (o *TweetInterstitialRevealText) GetEntities() []TweetInterstitialTextEntity {
	if o == nil {
		var ret []TweetInterstitialTextEntity
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *TweetInterstitialRevealText) GetEntitiesOk() ([]TweetInterstitialTextEntity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *TweetInterstitialRevealText) SetEntities(v []TweetInterstitialTextEntity) {
	o.Entities = v
}

// GetRtl returns the Rtl field value
func (o *TweetInterstitialRevealText) GetRtl() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Rtl
}

// GetRtlOk returns a tuple with the Rtl field value
// and a boolean to check if the value has been set.
func (o *TweetInterstitialRevealText) GetRtlOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rtl, true
}

// SetRtl sets field value
func (o *TweetInterstitialRevealText) SetRtl(v bool) {
	o.Rtl = v
}

// GetText returns the Text field value
func (o *TweetInterstitialRevealText) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *TweetInterstitialRevealText) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *TweetInterstitialRevealText) SetText(v string) {
	o.Text = v
}

func (o TweetInterstitialRevealText) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TweetInterstitialRevealText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entities"] = o.Entities
	toSerialize["rtl"] = o.Rtl
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *TweetInterstitialRevealText) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entities",
		"rtl",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTweetInterstitialRevealText := _TweetInterstitialRevealText{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTweetInterstitialRevealText)

	if err != nil {
		return err
	}

	*o = TweetInterstitialRevealText(varTweetInterstitialRevealText)

	return err
}

type NullableTweetInterstitialRevealText struct {
	value *TweetInterstitialRevealText
	isSet bool
}

func (v NullableTweetInterstitialRevealText) Get() *TweetInterstitialRevealText {
	return v.value
}

func (v *NullableTweetInterstitialRevealText) Set(val *TweetInterstitialRevealText) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetInterstitialRevealText) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetInterstitialRevealText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetInterstitialRevealText(val *TweetInterstitialRevealText) *NullableTweetInterstitialRevealText {
	return &NullableTweetInterstitialRevealText{value: val, isSet: true}
}

func (v NullableTweetInterstitialRevealText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetInterstitialRevealText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
