/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GetUserHighlightsTweets200Response - struct for GetUserHighlightsTweets200Response
type GetUserHighlightsTweets200Response struct {
	Errors *Errors
	UserHighlightsTweetsResponse *UserHighlightsTweetsResponse
}

// ErrorsAsGetUserHighlightsTweets200Response is a convenience function that returns Errors wrapped in GetUserHighlightsTweets200Response
func ErrorsAsGetUserHighlightsTweets200Response(v *Errors) GetUserHighlightsTweets200Response {
	return GetUserHighlightsTweets200Response{
		Errors: v,
	}
}

// UserHighlightsTweetsResponseAsGetUserHighlightsTweets200Response is a convenience function that returns UserHighlightsTweetsResponse wrapped in GetUserHighlightsTweets200Response
func UserHighlightsTweetsResponseAsGetUserHighlightsTweets200Response(v *UserHighlightsTweetsResponse) GetUserHighlightsTweets200Response {
	return GetUserHighlightsTweets200Response{
		UserHighlightsTweetsResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetUserHighlightsTweets200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Errors
	err = newStrictDecoder(data).Decode(&dst.Errors)
	if err == nil {
		jsonErrors, _ := json.Marshal(dst.Errors)
		if string(jsonErrors) == "{}" { // empty struct
			dst.Errors = nil
		} else {
			if err = validator.Validate(dst.Errors); err != nil {
				dst.Errors = nil
			} else {
				match++
			}
		}
	} else {
		dst.Errors = nil
	}

	// try to unmarshal data into UserHighlightsTweetsResponse
	err = newStrictDecoder(data).Decode(&dst.UserHighlightsTweetsResponse)
	if err == nil {
		jsonUserHighlightsTweetsResponse, _ := json.Marshal(dst.UserHighlightsTweetsResponse)
		if string(jsonUserHighlightsTweetsResponse) == "{}" { // empty struct
			dst.UserHighlightsTweetsResponse = nil
		} else {
			if err = validator.Validate(dst.UserHighlightsTweetsResponse); err != nil {
				dst.UserHighlightsTweetsResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.UserHighlightsTweetsResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Errors = nil
		dst.UserHighlightsTweetsResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetUserHighlightsTweets200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetUserHighlightsTweets200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetUserHighlightsTweets200Response) MarshalJSON() ([]byte, error) {
	if src.Errors != nil {
		return json.Marshal(&src.Errors)
	}

	if src.UserHighlightsTweetsResponse != nil {
		return json.Marshal(&src.UserHighlightsTweetsResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetUserHighlightsTweets200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Errors != nil {
		return obj.Errors
	}

	if obj.UserHighlightsTweetsResponse != nil {
		return obj.UserHighlightsTweetsResponse
	}

	// all schemas are nil
	return nil
}

type NullableGetUserHighlightsTweets200Response struct {
	value *GetUserHighlightsTweets200Response
	isSet bool
}

func (v NullableGetUserHighlightsTweets200Response) Get() *GetUserHighlightsTweets200Response {
	return v.value
}

func (v *NullableGetUserHighlightsTweets200Response) Set(val *GetUserHighlightsTweets200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserHighlightsTweets200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserHighlightsTweets200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserHighlightsTweets200Response(val *GetUserHighlightsTweets200Response) *NullableGetUserHighlightsTweets200Response {
	return &NullableGetUserHighlightsTweets200Response{value: val, isSet: true}
}

func (v NullableGetUserHighlightsTweets200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserHighlightsTweets200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


