/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostCreateTweetRequestVariablesMediaMediaEntitiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCreateTweetRequestVariablesMediaMediaEntitiesInner{}

// PostCreateTweetRequestVariablesMediaMediaEntitiesInner struct for PostCreateTweetRequestVariablesMediaMediaEntitiesInner
type PostCreateTweetRequestVariablesMediaMediaEntitiesInner struct {
	MediaId     string   `json:"media_id"`
	TaggedUsers []string `json:"tagged_users"`
}

type _PostCreateTweetRequestVariablesMediaMediaEntitiesInner PostCreateTweetRequestVariablesMediaMediaEntitiesInner

// NewPostCreateTweetRequestVariablesMediaMediaEntitiesInner instantiates a new PostCreateTweetRequestVariablesMediaMediaEntitiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCreateTweetRequestVariablesMediaMediaEntitiesInner(mediaId string, taggedUsers []string) *PostCreateTweetRequestVariablesMediaMediaEntitiesInner {
	this := PostCreateTweetRequestVariablesMediaMediaEntitiesInner{}
	this.MediaId = mediaId
	this.TaggedUsers = taggedUsers
	return &this
}

// NewPostCreateTweetRequestVariablesMediaMediaEntitiesInnerWithDefaults instantiates a new PostCreateTweetRequestVariablesMediaMediaEntitiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCreateTweetRequestVariablesMediaMediaEntitiesInnerWithDefaults() *PostCreateTweetRequestVariablesMediaMediaEntitiesInner {
	this := PostCreateTweetRequestVariablesMediaMediaEntitiesInner{}
	var mediaId string = "1111111111111111111"
	this.MediaId = mediaId
	return &this
}

// GetMediaId returns the MediaId field value
func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) GetMediaId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value
// and a boolean to check if the value has been set.
func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) GetMediaIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaId, true
}

// SetMediaId sets field value
func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) SetMediaId(v string) {
	o.MediaId = v
}

// GetTaggedUsers returns the TaggedUsers field value
func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) GetTaggedUsers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TaggedUsers
}

// GetTaggedUsersOk returns a tuple with the TaggedUsers field value
// and a boolean to check if the value has been set.
func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) GetTaggedUsersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaggedUsers, true
}

// SetTaggedUsers sets field value
func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) SetTaggedUsers(v []string) {
	o.TaggedUsers = v
}

func (o PostCreateTweetRequestVariablesMediaMediaEntitiesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCreateTweetRequestVariablesMediaMediaEntitiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["media_id"] = o.MediaId
	toSerialize["tagged_users"] = o.TaggedUsers
	return toSerialize, nil
}

func (o *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"media_id",
		"tagged_users",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCreateTweetRequestVariablesMediaMediaEntitiesInner := _PostCreateTweetRequestVariablesMediaMediaEntitiesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCreateTweetRequestVariablesMediaMediaEntitiesInner)

	if err != nil {
		return err
	}

	*o = PostCreateTweetRequestVariablesMediaMediaEntitiesInner(varPostCreateTweetRequestVariablesMediaMediaEntitiesInner)

	return err
}

type NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner struct {
	value *PostCreateTweetRequestVariablesMediaMediaEntitiesInner
	isSet bool
}

func (v NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner) Get() *PostCreateTweetRequestVariablesMediaMediaEntitiesInner {
	return v.value
}

func (v *NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner) Set(val *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner(val *PostCreateTweetRequestVariablesMediaMediaEntitiesInner) *NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner {
	return &NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner{value: val, isSet: true}
}

func (v NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCreateTweetRequestVariablesMediaMediaEntitiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
