/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TweetCardLegacyBindingValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TweetCardLegacyBindingValue{}

// TweetCardLegacyBindingValue struct for TweetCardLegacyBindingValue
type TweetCardLegacyBindingValue struct {
	Key string `json:"key"`
	Value TweetCardLegacyBindingValueData `json:"value"`
}

type _TweetCardLegacyBindingValue TweetCardLegacyBindingValue

// NewTweetCardLegacyBindingValue instantiates a new TweetCardLegacyBindingValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetCardLegacyBindingValue(key string, value TweetCardLegacyBindingValueData) *TweetCardLegacyBindingValue {
	this := TweetCardLegacyBindingValue{}
	this.Key = key
	this.Value = value
	return &this
}

// NewTweetCardLegacyBindingValueWithDefaults instantiates a new TweetCardLegacyBindingValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetCardLegacyBindingValueWithDefaults() *TweetCardLegacyBindingValue {
	this := TweetCardLegacyBindingValue{}
	return &this
}

// GetKey returns the Key field value
func (o *TweetCardLegacyBindingValue) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *TweetCardLegacyBindingValue) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *TweetCardLegacyBindingValue) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *TweetCardLegacyBindingValue) GetValue() TweetCardLegacyBindingValueData {
	if o == nil {
		var ret TweetCardLegacyBindingValueData
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *TweetCardLegacyBindingValue) GetValueOk() (*TweetCardLegacyBindingValueData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *TweetCardLegacyBindingValue) SetValue(v TweetCardLegacyBindingValueData) {
	o.Value = v
}

func (o TweetCardLegacyBindingValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TweetCardLegacyBindingValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *TweetCardLegacyBindingValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTweetCardLegacyBindingValue := _TweetCardLegacyBindingValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTweetCardLegacyBindingValue)

	if err != nil {
		return err
	}

	*o = TweetCardLegacyBindingValue(varTweetCardLegacyBindingValue)

	return err
}

type NullableTweetCardLegacyBindingValue struct {
	value *TweetCardLegacyBindingValue
	isSet bool
}

func (v NullableTweetCardLegacyBindingValue) Get() *TweetCardLegacyBindingValue {
	return v.value
}

func (v *NullableTweetCardLegacyBindingValue) Set(val *TweetCardLegacyBindingValue) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetCardLegacyBindingValue) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetCardLegacyBindingValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetCardLegacyBindingValue(val *TweetCardLegacyBindingValue) *NullableTweetCardLegacyBindingValue {
	return &NullableTweetCardLegacyBindingValue{value: val, isSet: true}
}

func (v NullableTweetCardLegacyBindingValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetCardLegacyBindingValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


