/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityUrls{}

// CommunityUrls struct for CommunityUrls
type CommunityUrls struct {
	Permalink CommunityUrlsPermalink `json:"permalink"`
}

type _CommunityUrls CommunityUrls

// NewCommunityUrls instantiates a new CommunityUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityUrls(permalink CommunityUrlsPermalink) *CommunityUrls {
	this := CommunityUrls{}
	this.Permalink = permalink
	return &this
}

// NewCommunityUrlsWithDefaults instantiates a new CommunityUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityUrlsWithDefaults() *CommunityUrls {
	this := CommunityUrls{}
	return &this
}

// GetPermalink returns the Permalink field value
func (o *CommunityUrls) GetPermalink() CommunityUrlsPermalink {
	if o == nil {
		var ret CommunityUrlsPermalink
		return ret
	}

	return o.Permalink
}

// GetPermalinkOk returns a tuple with the Permalink field value
// and a boolean to check if the value has been set.
func (o *CommunityUrls) GetPermalinkOk() (*CommunityUrlsPermalink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Permalink, true
}

// SetPermalink sets field value
func (o *CommunityUrls) SetPermalink(v CommunityUrlsPermalink) {
	o.Permalink = v
}

func (o CommunityUrls) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permalink"] = o.Permalink
	return toSerialize, nil
}

func (o *CommunityUrls) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permalink",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityUrls := _CommunityUrls{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityUrls)

	if err != nil {
		return err
	}

	*o = CommunityUrls(varCommunityUrls)

	return err
}

type NullableCommunityUrls struct {
	value *CommunityUrls
	isSet bool
}

func (v NullableCommunityUrls) Get() *CommunityUrls {
	return v.value
}

func (v *NullableCommunityUrls) Set(val *CommunityUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityUrls(val *CommunityUrls) *NullableCommunityUrls {
	return &NullableCommunityUrls{value: val, isSet: true}
}

func (v NullableCommunityUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


