/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostDeleteBookmark200Response - struct for PostDeleteBookmark200Response
type PostDeleteBookmark200Response struct {
	DeleteBookmarkResponse *DeleteBookmarkResponse
	Errors                 *Errors
}

// DeleteBookmarkResponseAsPostDeleteBookmark200Response is a convenience function that returns DeleteBookmarkResponse wrapped in PostDeleteBookmark200Response
func DeleteBookmarkResponseAsPostDeleteBookmark200Response(v *DeleteBookmarkResponse) PostDeleteBookmark200Response {
	return PostDeleteBookmark200Response{
		DeleteBookmarkResponse: v,
	}
}

// ErrorsAsPostDeleteBookmark200Response is a convenience function that returns Errors wrapped in PostDeleteBookmark200Response
func ErrorsAsPostDeleteBookmark200Response(v *Errors) PostDeleteBookmark200Response {
	return PostDeleteBookmark200Response{
		Errors: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostDeleteBookmark200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DeleteBookmarkResponse
	err = newStrictDecoder(data).Decode(&dst.DeleteBookmarkResponse)
	if err == nil {
		jsonDeleteBookmarkResponse, _ := json.Marshal(dst.DeleteBookmarkResponse)
		if string(jsonDeleteBookmarkResponse) == "{}" { // empty struct
			dst.DeleteBookmarkResponse = nil
		} else {
			if err = validator.Validate(dst.DeleteBookmarkResponse); err != nil {
				dst.DeleteBookmarkResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeleteBookmarkResponse = nil
	}

	// try to unmarshal data into Errors
	err = newStrictDecoder(data).Decode(&dst.Errors)
	if err == nil {
		jsonErrors, _ := json.Marshal(dst.Errors)
		if string(jsonErrors) == "{}" { // empty struct
			dst.Errors = nil
		} else {
			if err = validator.Validate(dst.Errors); err != nil {
				dst.Errors = nil
			} else {
				match++
			}
		}
	} else {
		dst.Errors = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeleteBookmarkResponse = nil
		dst.Errors = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostDeleteBookmark200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostDeleteBookmark200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostDeleteBookmark200Response) MarshalJSON() ([]byte, error) {
	if src.DeleteBookmarkResponse != nil {
		return json.Marshal(&src.DeleteBookmarkResponse)
	}

	if src.Errors != nil {
		return json.Marshal(&src.Errors)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostDeleteBookmark200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DeleteBookmarkResponse != nil {
		return obj.DeleteBookmarkResponse
	}

	if obj.Errors != nil {
		return obj.Errors
	}

	// all schemas are nil
	return nil
}

type NullablePostDeleteBookmark200Response struct {
	value *PostDeleteBookmark200Response
	isSet bool
}

func (v NullablePostDeleteBookmark200Response) Get() *PostDeleteBookmark200Response {
	return v.value
}

func (v *NullablePostDeleteBookmark200Response) Set(val *PostDeleteBookmark200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostDeleteBookmark200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostDeleteBookmark200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostDeleteBookmark200Response(val *PostDeleteBookmark200Response) *NullablePostDeleteBookmark200Response {
	return &NullablePostDeleteBookmark200Response{value: val, isSet: true}
}

func (v NullablePostDeleteBookmark200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostDeleteBookmark200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
