/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// UserUnion - struct for UserUnion
type UserUnion struct {
	User *User
	UserUnavailable *UserUnavailable
}

// UserAsUserUnion is a convenience function that returns User wrapped in UserUnion
func UserAsUserUnion(v *User) UserUnion {
	return UserUnion{
		User: v,
	}
}

// UserUnavailableAsUserUnion is a convenience function that returns UserUnavailable wrapped in UserUnion
func UserUnavailableAsUserUnion(v *UserUnavailable) UserUnion {
	return UserUnion{
		UserUnavailable: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *UserUnion) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into User
	err = newStrictDecoder(data).Decode(&dst.User)
	if err == nil {
		jsonUser, _ := json.Marshal(dst.User)
		if string(jsonUser) == "{}" { // empty struct
			dst.User = nil
		} else {
			if err = validator.Validate(dst.User); err != nil {
				dst.User = nil
			} else {
				match++
			}
		}
	} else {
		dst.User = nil
	}

	// try to unmarshal data into UserUnavailable
	err = newStrictDecoder(data).Decode(&dst.UserUnavailable)
	if err == nil {
		jsonUserUnavailable, _ := json.Marshal(dst.UserUnavailable)
		if string(jsonUserUnavailable) == "{}" { // empty struct
			dst.UserUnavailable = nil
		} else {
			if err = validator.Validate(dst.UserUnavailable); err != nil {
				dst.UserUnavailable = nil
			} else {
				match++
			}
		}
	} else {
		dst.UserUnavailable = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.User = nil
		dst.UserUnavailable = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UserUnion)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UserUnion)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UserUnion) MarshalJSON() ([]byte, error) {
	if src.User != nil {
		return json.Marshal(&src.User)
	}

	if src.UserUnavailable != nil {
		return json.Marshal(&src.UserUnavailable)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UserUnion) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.User != nil {
		return obj.User
	}

	if obj.UserUnavailable != nil {
		return obj.UserUnavailable
	}

	// all schemas are nil
	return nil
}

type NullableUserUnion struct {
	value *UserUnion
	isSet bool
}

func (v NullableUserUnion) Get() *UserUnion {
	return v.value
}

func (v *NullableUserUnion) Set(val *UserUnion) {
	v.value = val
	v.isSet = true
}

func (v NullableUserUnion) IsSet() bool {
	return v.isSet
}

func (v *NullableUserUnion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserUnion(val *UserUnion) *NullableUserUnion {
	return &NullableUserUnion{value: val, isSet: true}
}

func (v NullableUserUnion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserUnion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


