/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HomeTimelineResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HomeTimelineResponseData{}

// HomeTimelineResponseData struct for HomeTimelineResponseData
type HomeTimelineResponseData struct {
	Home HomeTimelineHome `json:"home"`
}

type _HomeTimelineResponseData HomeTimelineResponseData

// NewHomeTimelineResponseData instantiates a new HomeTimelineResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHomeTimelineResponseData(home HomeTimelineHome) *HomeTimelineResponseData {
	this := HomeTimelineResponseData{}
	this.Home = home
	return &this
}

// NewHomeTimelineResponseDataWithDefaults instantiates a new HomeTimelineResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHomeTimelineResponseDataWithDefaults() *HomeTimelineResponseData {
	this := HomeTimelineResponseData{}
	return &this
}

// GetHome returns the Home field value
func (o *HomeTimelineResponseData) GetHome() HomeTimelineHome {
	if o == nil {
		var ret HomeTimelineHome
		return ret
	}

	return o.Home
}

// GetHomeOk returns a tuple with the Home field value
// and a boolean to check if the value has been set.
func (o *HomeTimelineResponseData) GetHomeOk() (*HomeTimelineHome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Home, true
}

// SetHome sets field value
func (o *HomeTimelineResponseData) SetHome(v HomeTimelineHome) {
	o.Home = v
}

func (o HomeTimelineResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HomeTimelineResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["home"] = o.Home
	return toSerialize, nil
}

func (o *HomeTimelineResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"home",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHomeTimelineResponseData := _HomeTimelineResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHomeTimelineResponseData)

	if err != nil {
		return err
	}

	*o = HomeTimelineResponseData(varHomeTimelineResponseData)

	return err
}

type NullableHomeTimelineResponseData struct {
	value *HomeTimelineResponseData
	isSet bool
}

func (v NullableHomeTimelineResponseData) Get() *HomeTimelineResponseData {
	return v.value
}

func (v *NullableHomeTimelineResponseData) Set(val *HomeTimelineResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableHomeTimelineResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableHomeTimelineResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHomeTimelineResponseData(val *HomeTimelineResponseData) *NullableHomeTimelineResponseData {
	return &NullableHomeTimelineResponseData{value: val, isSet: true}
}

func (v NullableHomeTimelineResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHomeTimelineResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
