/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TimelineTerminateTimeline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineTerminateTimeline{}

// TimelineTerminateTimeline struct for TimelineTerminateTimeline
type TimelineTerminateTimeline struct {
	Direction string          `json:"direction"`
	Type      InstructionType `json:"type"`
}

type _TimelineTerminateTimeline TimelineTerminateTimeline

// NewTimelineTerminateTimeline instantiates a new TimelineTerminateTimeline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineTerminateTimeline(direction string, type_ InstructionType) *TimelineTerminateTimeline {
	this := TimelineTerminateTimeline{}
	this.Direction = direction
	this.Type = type_
	return &this
}

// NewTimelineTerminateTimelineWithDefaults instantiates a new TimelineTerminateTimeline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineTerminateTimelineWithDefaults() *TimelineTerminateTimeline {
	this := TimelineTerminateTimeline{}
	return &this
}

// GetDirection returns the Direction field value
func (o *TimelineTerminateTimeline) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *TimelineTerminateTimeline) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *TimelineTerminateTimeline) SetDirection(v string) {
	o.Direction = v
}

// GetType returns the Type field value
func (o *TimelineTerminateTimeline) GetType() InstructionType {
	if o == nil {
		var ret InstructionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TimelineTerminateTimeline) GetTypeOk() (*InstructionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TimelineTerminateTimeline) SetType(v InstructionType) {
	o.Type = v
}

func (o TimelineTerminateTimeline) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineTerminateTimeline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["direction"] = o.Direction
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TimelineTerminateTimeline) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"direction",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimelineTerminateTimeline := _TimelineTerminateTimeline{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimelineTerminateTimeline)

	if err != nil {
		return err
	}

	*o = TimelineTerminateTimeline(varTimelineTerminateTimeline)

	return err
}

type NullableTimelineTerminateTimeline struct {
	value *TimelineTerminateTimeline
	isSet bool
}

func (v NullableTimelineTerminateTimeline) Get() *TimelineTerminateTimeline {
	return v.value
}

func (v *NullableTimelineTerminateTimeline) Set(val *TimelineTerminateTimeline) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineTerminateTimeline) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineTerminateTimeline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineTerminateTimeline(val *TimelineTerminateTimeline) *NullableTimelineTerminateTimeline {
	return &NullableTimelineTerminateTimeline{value: val, isSet: true}
}

func (v NullableTimelineTerminateTimeline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineTerminateTimeline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
