/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListTweetsTimelineList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTweetsTimelineList{}

// ListTweetsTimelineList struct for ListTweetsTimelineList
type ListTweetsTimelineList struct {
	TweetsTimeline ListTweetsTimeline `json:"tweets_timeline"`
}

type _ListTweetsTimelineList ListTweetsTimelineList

// NewListTweetsTimelineList instantiates a new ListTweetsTimelineList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTweetsTimelineList(tweetsTimeline ListTweetsTimeline) *ListTweetsTimelineList {
	this := ListTweetsTimelineList{}
	this.TweetsTimeline = tweetsTimeline
	return &this
}

// NewListTweetsTimelineListWithDefaults instantiates a new ListTweetsTimelineList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTweetsTimelineListWithDefaults() *ListTweetsTimelineList {
	this := ListTweetsTimelineList{}
	return &this
}

// GetTweetsTimeline returns the TweetsTimeline field value
func (o *ListTweetsTimelineList) GetTweetsTimeline() ListTweetsTimeline {
	if o == nil {
		var ret ListTweetsTimeline
		return ret
	}

	return o.TweetsTimeline
}

// GetTweetsTimelineOk returns a tuple with the TweetsTimeline field value
// and a boolean to check if the value has been set.
func (o *ListTweetsTimelineList) GetTweetsTimelineOk() (*ListTweetsTimeline, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TweetsTimeline, true
}

// SetTweetsTimeline sets field value
func (o *ListTweetsTimelineList) SetTweetsTimeline(v ListTweetsTimeline) {
	o.TweetsTimeline = v
}

func (o ListTweetsTimelineList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTweetsTimelineList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tweets_timeline"] = o.TweetsTimeline
	return toSerialize, nil
}

func (o *ListTweetsTimelineList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tweets_timeline",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTweetsTimelineList := _ListTweetsTimelineList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListTweetsTimelineList)

	if err != nil {
		return err
	}

	*o = ListTweetsTimelineList(varListTweetsTimelineList)

	return err
}

type NullableListTweetsTimelineList struct {
	value *ListTweetsTimelineList
	isSet bool
}

func (v NullableListTweetsTimelineList) Get() *ListTweetsTimelineList {
	return v.value
}

func (v *NullableListTweetsTimelineList) Set(val *ListTweetsTimelineList) {
	v.value = val
	v.isSet = true
}

func (v NullableListTweetsTimelineList) IsSet() bool {
	return v.isSet
}

func (v *NullableListTweetsTimelineList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTweetsTimelineList(val *ListTweetsTimelineList) *NullableListTweetsTimelineList {
	return &NullableListTweetsTimelineList{value: val, isSet: true}
}

func (v NullableListTweetsTimelineList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTweetsTimelineList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
