/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeleteBookmarkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteBookmarkResponse{}

// DeleteBookmarkResponse struct for DeleteBookmarkResponse
type DeleteBookmarkResponse struct {
	Data DeleteBookmarkResponseData `json:"data"`
}

type _DeleteBookmarkResponse DeleteBookmarkResponse

// NewDeleteBookmarkResponse instantiates a new DeleteBookmarkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteBookmarkResponse(data DeleteBookmarkResponseData) *DeleteBookmarkResponse {
	this := DeleteBookmarkResponse{}
	this.Data = data
	return &this
}

// NewDeleteBookmarkResponseWithDefaults instantiates a new DeleteBookmarkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteBookmarkResponseWithDefaults() *DeleteBookmarkResponse {
	this := DeleteBookmarkResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteBookmarkResponse) GetData() DeleteBookmarkResponseData {
	if o == nil {
		var ret DeleteBookmarkResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteBookmarkResponse) GetDataOk() (*DeleteBookmarkResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteBookmarkResponse) SetData(v DeleteBookmarkResponseData) {
	o.Data = v
}

func (o DeleteBookmarkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteBookmarkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteBookmarkResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteBookmarkResponse := _DeleteBookmarkResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteBookmarkResponse)

	if err != nil {
		return err
	}

	*o = DeleteBookmarkResponse(varDeleteBookmarkResponse)

	return err
}

type NullableDeleteBookmarkResponse struct {
	value *DeleteBookmarkResponse
	isSet bool
}

func (v NullableDeleteBookmarkResponse) Get() *DeleteBookmarkResponse {
	return v.value
}

func (v *NullableDeleteBookmarkResponse) Set(val *DeleteBookmarkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteBookmarkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteBookmarkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteBookmarkResponse(val *DeleteBookmarkResponse) *NullableDeleteBookmarkResponse {
	return &NullableDeleteBookmarkResponse{value: val, isSet: true}
}

func (v NullableDeleteBookmarkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteBookmarkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
