/*
Twitter OpenAPI

Twitter OpenAPI(Swagger) specification

API version: 0.0.1
Contact: yuki@yuki0311.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityUrlsPermalink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityUrlsPermalink{}

// CommunityUrlsPermalink struct for CommunityUrlsPermalink
type CommunityUrlsPermalink struct {
	Url string `json:"url"`
}

type _CommunityUrlsPermalink CommunityUrlsPermalink

// NewCommunityUrlsPermalink instantiates a new CommunityUrlsPermalink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityUrlsPermalink(url string) *CommunityUrlsPermalink {
	this := CommunityUrlsPermalink{}
	this.Url = url
	return &this
}

// NewCommunityUrlsPermalinkWithDefaults instantiates a new CommunityUrlsPermalink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityUrlsPermalinkWithDefaults() *CommunityUrlsPermalink {
	this := CommunityUrlsPermalink{}
	return &this
}

// GetUrl returns the Url field value
func (o *CommunityUrlsPermalink) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CommunityUrlsPermalink) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CommunityUrlsPermalink) SetUrl(v string) {
	o.Url = v
}

func (o CommunityUrlsPermalink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityUrlsPermalink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *CommunityUrlsPermalink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityUrlsPermalink := _CommunityUrlsPermalink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityUrlsPermalink)

	if err != nil {
		return err
	}

	*o = CommunityUrlsPermalink(varCommunityUrlsPermalink)

	return err
}

type NullableCommunityUrlsPermalink struct {
	value *CommunityUrlsPermalink
	isSet bool
}

func (v NullableCommunityUrlsPermalink) Get() *CommunityUrlsPermalink {
	return v.value
}

func (v *NullableCommunityUrlsPermalink) Set(val *CommunityUrlsPermalink) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityUrlsPermalink) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityUrlsPermalink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityUrlsPermalink(val *CommunityUrlsPermalink) *NullableCommunityUrlsPermalink {
	return &NullableCommunityUrlsPermalink{value: val, isSet: true}
}

func (v NullableCommunityUrlsPermalink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityUrlsPermalink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


